/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.hammercraftfantasy.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.hammercraftfantasy.item.*;
import net.mcreator.hammercraftfantasy.HammercraftfantasyMod;

public class HammercraftfantasyModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(HammercraftfantasyMod.MODID);
	public static final DeferredItem<Item> SKARBRAND_SPAWN_EGG;
	public static final DeferredItem<Item> DEMON_ESSENCE;
	public static final DeferredItem<Item> HELL_BLADE;
	public static final DeferredItem<Item> BLOODLETTER_SPAWN_EGG;
	public static final DeferredItem<Item> UNKNOW_BEAUTY_SPAWN_EGG;
	public static final DeferredItem<Item> DEMONEZ_SPAWN_EGG;
	public static final DeferredItem<Item> HERALDOF_KHORNE_SPAWN_EGG;
	public static final DeferredItem<Item> NURGLING_SPAWN_EGG;
	public static final DeferredItem<Item> PINK_HORROR_SPAWN_EGG;
	public static final DeferredItem<Item> BLUE_HORROR_SPAWN_EGG;
	public static final DeferredItem<Item> CHAOSTHORN;
	public static final DeferredItem<Item> RAGEANDFURY_HELMET;
	public static final DeferredItem<Item> RAGEANDFURY_CHESTPLATE;
	public static final DeferredItem<Item> RAGEANDFURY_LEGGINGS;
	public static final DeferredItem<Item> RAGEANDFURY_BOOTS;
	public static final DeferredItem<Item> CORRUPTIONANDROT_HELMET;
	public static final DeferredItem<Item> CORRUPTIONANDROT_CHESTPLATE;
	public static final DeferredItem<Item> CORRUPTIONANDROT_LEGGINGS;
	public static final DeferredItem<Item> CORRUPTIONANDROT_BOOTS;
	public static final DeferredItem<Item> OBSESSIONANDDESIRE_HELMET;
	public static final DeferredItem<Item> OBSESSIONANDDESIRE_CHESTPLATE;
	public static final DeferredItem<Item> OBSESSIONANDDESIRE_LEGGINGS;
	public static final DeferredItem<Item> OBSESSIONANDDESIRE_BOOTS;
	public static final DeferredItem<Item> DECEITANDSCHEME_HELMET;
	public static final DeferredItem<Item> DECEITANDSCHEME_CHESTPLATE;
	public static final DeferredItem<Item> DECEITANDSCHEME_LEGGINGS;
	public static final DeferredItem<Item> DECEITANDSCHEME_BOOTS;
	public static final DeferredItem<Item> FLESHHOUNDS_SPAWN_EGG;
	public static final DeferredItem<Item> RAGEESSENCE;
	public static final DeferredItem<Item> RAGEINGOT;
	public static final DeferredItem<Item> KHORNETEMPLATE;
	public static final DeferredItem<Item> DECEITESSENCE;
	public static final DeferredItem<Item> DECEITINGOT;
	public static final DeferredItem<Item> TZEENTCHTEMPLATE;
	public static final DeferredItem<Item> OBSESSIONESSENCE;
	public static final DeferredItem<Item> OBSESSIONINGOT;
	public static final DeferredItem<Item> SLAANESHTEMPLATE;
	public static final DeferredItem<Item> CORRUPTIONESSENCE;
	public static final DeferredItem<Item> CORRUPTIONINGOT;
	public static final DeferredItem<Item> NURGLETEMPLATE;
	public static final DeferredItem<Item> RAGEBATTLEAXE;
	public static final DeferredItem<Item> RAGEMATTER;
	public static final DeferredItem<Item> DECEITMATTER;
	public static final DeferredItem<Item> OBSESSIONMATTER;
	public static final DeferredItem<Item> CORRUPTIONMATTER;
	public static final DeferredItem<Item> DEMONSMETALNUGGET;
	public static final DeferredItem<Item> DEMONSMETALINGOT;
	public static final DeferredItem<Item> KCHAOSWARRIOR_SPAWN_EGG;
	public static final DeferredItem<Item> KCULTIST_SPAWN_EGG;
	public static final DeferredItem<Item> CRYSTALSAND;
	public static final DeferredItem<Item> ROTFLY_SPAWN_EGG;
	public static final DeferredItem<Item> PLAGUELOG;
	public static final DeferredItem<Item> PLAGUEBEARER_SPAWN_EGG;
	public static final DeferredItem<Item> PLAGUELEAVES;
	public static final DeferredItem<Item> GREATUNCLEANONE_SPAWN_EGG;
	public static final DeferredItem<Item> ROTMAGGOT_SPAWN_EGG;
	public static final DeferredItem<Item> PLAGUEZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> ROTFLYNEST;
	public static final DeferredItem<Item> DIVINEPLAGUE;
	public static final DeferredItem<Item> GRANDFATHERSSOUP;
	public static final DeferredItem<Item> GARDENERSHOE;
	public static final DeferredItem<Item> PLAGUEPLANKS;
	public static final DeferredItem<Item> NAGOXO_SPAWN_EGG;
	public static final DeferredItem<Item> CHAOSSPAWN_SPAWN_EGG;
	public static final DeferredItem<Item> FORSAKEN_SPAWN_EGG;
	public static final DeferredItem<Item> KEYOFGARDEN;
	public static final DeferredItem<Item> FIENDOFSLAANESH_SPAWN_EGG;
	public static final DeferredItem<Item> DEAMONETTE_SPAWN_EGG;
	public static final DeferredItem<Item> STEEDOFSLAANESH_SPAWN_EGG;
	public static final DeferredItem<Item> TAMURKHAN_SPAWN_EGG;
	public static final DeferredItem<Item> VALKIA_SPAWN_EGG;
	public static final DeferredItem<Item> SIGVALD_SPAWN_EGG;
	public static final DeferredItem<Item> SILVERGUARD_SPAWN_EGG;
	public static final DeferredItem<Item> SCREAMER_SPAWN_EGG;
	public static final DeferredItem<Item> FLAMER_SPAWN_EGG;
	public static final DeferredItem<Item> TZAANGOR_SPAWN_EGG;
	public static final DeferredItem<Item> ERIC_SPAWN_EGG;
	public static final DeferredItem<Item> ERICSPAWN_SPAWN_EGG;
	public static final DeferredItem<Item> MAGGOTLORD_SPAWN_EGG;
	public static final DeferredItem<Item> TZAANGORHALBERD_SPAWN_EGG;
	public static final DeferredItem<Item> KEYOFTHRONE;
	public static final DeferredItem<Item> KEYOFLIBRARY;
	public static final DeferredItem<Item> KEYOFPALACE;
	public static final DeferredItem<Item> DEMONSTEELSWORD;
	public static final DeferredItem<Item> DEMONSTEELAXE;
	public static final DeferredItem<Item> DEMONSTEELPICKAXE;
	public static final DeferredItem<Item> DEMONSTEELSHOVEL;
	public static final DeferredItem<Item> DEMONSTEELHOE;
	public static final DeferredItem<Item> DEMONSTEELARMOR_HELMET;
	public static final DeferredItem<Item> DEMONSTEELARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DEMONSTEELARMOR_LEGGINGS;
	public static final DeferredItem<Item> DEMONSTEELARMOR_BOOTS;
	public static final DeferredItem<Item> CHANGINGGLASS;
	public static final DeferredItem<Item> MAZECRYSTAL;
	public static final DeferredItem<Item> RITUALDAGGER;
	public static final DeferredItem<Item> FLAMERSHEAD;
	public static final DeferredItem<Item> TRICKYSTONEBRICK;
	public static final DeferredItem<Item> KCHAMP_HELMET;
	public static final DeferredItem<Item> KCHAMP_CHESTPLATE;
	public static final DeferredItem<Item> KCHAMP_LEGGINGS;
	public static final DeferredItem<Item> KCHAMP_BOOTS;
	public static final DeferredItem<Item> NCHAMP_HELMET;
	public static final DeferredItem<Item> NCHAMP_CHESTPLATE;
	public static final DeferredItem<Item> NCHAMP_LEGGINGS;
	public static final DeferredItem<Item> NCHAMP_BOOTS;
	public static final DeferredItem<Item> TCHAMP_HELMET;
	public static final DeferredItem<Item> TCHAMP_CHESTPLATE;
	public static final DeferredItem<Item> TCHAMP_LEGGINGS;
	public static final DeferredItem<Item> TCHAMP_BOOTS;
	public static final DeferredItem<Item> SCHAMP_HELMET;
	public static final DeferredItem<Item> SCHAMP_CHESTPLATE;
	public static final DeferredItem<Item> SCHAMP_LEGGINGS;
	public static final DeferredItem<Item> SCHAMP_BOOTS;
	public static final DeferredItem<Item> ALTAROFSUFFERING;
	public static final DeferredItem<Item> K_CHAMPION_SUMMON_ALTAR;
	public static final DeferredItem<Item> N_CHAMPION_SUMMON_ALTAR;
	public static final DeferredItem<Item> T_CHAMPION_SUMMON_ALTAR;
	public static final DeferredItem<Item> S_CHAMPION_SUMMON_ALTAR;
	public static final DeferredItem<Item> RINGOFLUST_HELMET;
	public static final DeferredItem<Item> CRYSTALGRASS;
	public static final DeferredItem<Item> DEMONSTEELORE;
	public static final DeferredItem<Item> DEMONSTRUENAME;
	public static final DeferredItem<Item> SILVERSHARPSWORD;
	static {
		SKARBRAND_SPAWN_EGG = REGISTRY.register("skarbrand_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.SKARBRAND, -65536, -65536, new Item.Properties()));
		DEMON_ESSENCE = REGISTRY.register("demon_essence", DemonEssenceItem::new);
		HELL_BLADE = REGISTRY.register("hell_blade", HellBladeItem::new);
		BLOODLETTER_SPAWN_EGG = REGISTRY.register("bloodletter_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.BLOODLETTER, -10092544, -1, new Item.Properties()));
		UNKNOW_BEAUTY_SPAWN_EGG = REGISTRY.register("unknow_beauty_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.UNKNOW_BEAUTY, -1, -1, new Item.Properties()));
		DEMONEZ_SPAWN_EGG = REGISTRY.register("demonez_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.DEMONEZ, -1, -1, new Item.Properties()));
		HERALDOF_KHORNE_SPAWN_EGG = REGISTRY.register("heraldof_khorne_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.HERALDOF_KHORNE, -6750208, -10079488, new Item.Properties()));
		NURGLING_SPAWN_EGG = REGISTRY.register("nurgling_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.NURGLING, -13408768, -8091337, new Item.Properties()));
		PINK_HORROR_SPAWN_EGG = REGISTRY.register("pink_horror_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.PINK_HORROR, -26113, -3342337, new Item.Properties()));
		BLUE_HORROR_SPAWN_EGG = REGISTRY.register("blue_horror_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.BLUE_HORROR, -6684673, -26113, new Item.Properties()));
		CHAOSTHORN = block(HammercraftfantasyModBlocks.CHAOSTHORN);
		RAGEANDFURY_HELMET = REGISTRY.register("rageandfury_helmet", RageandfuryItem.Helmet::new);
		RAGEANDFURY_CHESTPLATE = REGISTRY.register("rageandfury_chestplate", RageandfuryItem.Chestplate::new);
		RAGEANDFURY_LEGGINGS = REGISTRY.register("rageandfury_leggings", RageandfuryItem.Leggings::new);
		RAGEANDFURY_BOOTS = REGISTRY.register("rageandfury_boots", RageandfuryItem.Boots::new);
		CORRUPTIONANDROT_HELMET = REGISTRY.register("corruptionandrot_helmet", CorruptionandrotItem.Helmet::new);
		CORRUPTIONANDROT_CHESTPLATE = REGISTRY.register("corruptionandrot_chestplate", CorruptionandrotItem.Chestplate::new);
		CORRUPTIONANDROT_LEGGINGS = REGISTRY.register("corruptionandrot_leggings", CorruptionandrotItem.Leggings::new);
		CORRUPTIONANDROT_BOOTS = REGISTRY.register("corruptionandrot_boots", CorruptionandrotItem.Boots::new);
		OBSESSIONANDDESIRE_HELMET = REGISTRY.register("obsessionanddesire_helmet", ObsessionanddesireItem.Helmet::new);
		OBSESSIONANDDESIRE_CHESTPLATE = REGISTRY.register("obsessionanddesire_chestplate", ObsessionanddesireItem.Chestplate::new);
		OBSESSIONANDDESIRE_LEGGINGS = REGISTRY.register("obsessionanddesire_leggings", ObsessionanddesireItem.Leggings::new);
		OBSESSIONANDDESIRE_BOOTS = REGISTRY.register("obsessionanddesire_boots", ObsessionanddesireItem.Boots::new);
		DECEITANDSCHEME_HELMET = REGISTRY.register("deceitandscheme_helmet", DeceitandschemeItem.Helmet::new);
		DECEITANDSCHEME_CHESTPLATE = REGISTRY.register("deceitandscheme_chestplate", DeceitandschemeItem.Chestplate::new);
		DECEITANDSCHEME_LEGGINGS = REGISTRY.register("deceitandscheme_leggings", DeceitandschemeItem.Leggings::new);
		DECEITANDSCHEME_BOOTS = REGISTRY.register("deceitandscheme_boots", DeceitandschemeItem.Boots::new);
		FLESHHOUNDS_SPAWN_EGG = REGISTRY.register("fleshhounds_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.FLESHHOUNDS, -6750208, -13434880, new Item.Properties()));
		RAGEESSENCE = REGISTRY.register("rageessence", RageessenceItem::new);
		RAGEINGOT = REGISTRY.register("rageingot", RageingotItem::new);
		KHORNETEMPLATE = REGISTRY.register("khornetemplate", KhornetemplateItem::new);
		DECEITESSENCE = REGISTRY.register("deceitessence", DeceitessenceItem::new);
		DECEITINGOT = REGISTRY.register("deceitingot", DeceitingotItem::new);
		TZEENTCHTEMPLATE = REGISTRY.register("tzeentchtemplate", TzeentchtemplateItem::new);
		OBSESSIONESSENCE = REGISTRY.register("obsessionessence", ObsessionessenceItem::new);
		OBSESSIONINGOT = REGISTRY.register("obsessioningot", ObsessioningotItem::new);
		SLAANESHTEMPLATE = REGISTRY.register("slaaneshtemplate", SlaaneshtemplateItem::new);
		CORRUPTIONESSENCE = REGISTRY.register("corruptionessence", CorruptionessenceItem::new);
		CORRUPTIONINGOT = REGISTRY.register("corruptioningot", CorruptioningotItem::new);
		NURGLETEMPLATE = REGISTRY.register("nurgletemplate", NurgletemplateItem::new);
		RAGEBATTLEAXE = REGISTRY.register("ragebattleaxe", RagebattleaxeItem::new);
		RAGEMATTER = REGISTRY.register("ragematter", RagematterItem::new);
		DECEITMATTER = REGISTRY.register("deceitmatter", DeceitmatterItem::new);
		OBSESSIONMATTER = REGISTRY.register("obsessionmatter", ObsessionmatterItem::new);
		CORRUPTIONMATTER = REGISTRY.register("corruptionmatter", CorruptionmatterItem::new);
		DEMONSMETALNUGGET = REGISTRY.register("demonsmetalnugget", DemonsmetalnuggetItem::new);
		DEMONSMETALINGOT = REGISTRY.register("demonsmetalingot", DemonsmetalingotItem::new);
		KCHAOSWARRIOR_SPAWN_EGG = REGISTRY.register("kchaoswarrior_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.KCHAOSWARRIOR, -10092544, -1, new Item.Properties()));
		KCULTIST_SPAWN_EGG = REGISTRY.register("kcultist_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.KCULTIST, -26215, -13434880, new Item.Properties()));
		CRYSTALSAND = block(HammercraftfantasyModBlocks.CRYSTALSAND);
		ROTFLY_SPAWN_EGG = REGISTRY.register("rotfly_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.ROTFLY, -13408768, -1, new Item.Properties()));
		PLAGUELOG = block(HammercraftfantasyModBlocks.PLAGUELOG);
		PLAGUEBEARER_SPAWN_EGG = REGISTRY.register("plaguebearer_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.PLAGUEBEARER, -13408768, -1, new Item.Properties()));
		PLAGUELEAVES = block(HammercraftfantasyModBlocks.PLAGUELEAVES);
		GREATUNCLEANONE_SPAWN_EGG = REGISTRY.register("greatuncleanone_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.GREATUNCLEANONE, -10066432, -13408768, new Item.Properties()));
		ROTMAGGOT_SPAWN_EGG = REGISTRY.register("rotmaggot_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.ROTMAGGOT, -13408768, -1, new Item.Properties()));
		PLAGUEZOMBIE_SPAWN_EGG = REGISTRY.register("plaguezombie_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.PLAGUEZOMBIE, -13408768, -1, new Item.Properties()));
		ROTFLYNEST = block(HammercraftfantasyModBlocks.ROTFLYNEST);
		DIVINEPLAGUE = REGISTRY.register("divineplague", DivineplagueItem::new);
		GRANDFATHERSSOUP = REGISTRY.register("grandfatherssoup", GrandfatherssoupItem::new);
		GARDENERSHOE = REGISTRY.register("gardenershoe", GardenershoeItem::new);
		PLAGUEPLANKS = block(HammercraftfantasyModBlocks.PLAGUEPLANKS);
		NAGOXO_SPAWN_EGG = REGISTRY.register("nagoxo_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.NAGOXO, -13408768, -1, new Item.Properties()));
		CHAOSSPAWN_SPAWN_EGG = REGISTRY.register("chaosspawn_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.CHAOSSPAWN, -13108, -1, new Item.Properties()));
		FORSAKEN_SPAWN_EGG = REGISTRY.register("forsaken_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.FORSAKEN, -13108, -1, new Item.Properties()));
		KEYOFGARDEN = REGISTRY.register("keyofgarden", KeyofgardenItem::new);
		FIENDOFSLAANESH_SPAWN_EGG = REGISTRY.register("fiendofslaanesh_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.FIENDOFSLAANESH, -26113, -1, new Item.Properties()));
		DEAMONETTE_SPAWN_EGG = REGISTRY.register("deamonette_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.DEAMONETTE, -26113, -1, new Item.Properties()));
		STEEDOFSLAANESH_SPAWN_EGG = REGISTRY.register("steedofslaanesh_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.STEEDOFSLAANESH, -26113, -1, new Item.Properties()));
		TAMURKHAN_SPAWN_EGG = REGISTRY.register("tamurkhan_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.TAMURKHAN, -10053376, -1, new Item.Properties()));
		VALKIA_SPAWN_EGG = REGISTRY.register("valkia_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.VALKIA, -65536, -13312, new Item.Properties()));
		SIGVALD_SPAWN_EGG = REGISTRY.register("sigvald_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.SIGVALD, -6750055, -1, new Item.Properties()));
		SILVERGUARD_SPAWN_EGG = REGISTRY.register("silverguard_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.SILVERGUARD, -6750055, -1, new Item.Properties()));
		SCREAMER_SPAWN_EGG = REGISTRY.register("screamer_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.SCREAMER, -16750900, -1, new Item.Properties()));
		FLAMER_SPAWN_EGG = REGISTRY.register("flamer_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.FLAMER, -16750900, -1, new Item.Properties()));
		TZAANGOR_SPAWN_EGG = REGISTRY.register("tzaangor_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.TZAANGOR, -16763956, -1, new Item.Properties()));
		ERIC_SPAWN_EGG = REGISTRY.register("eric_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.ERIC, -16769537, -1, new Item.Properties()));
		ERICSPAWN_SPAWN_EGG = REGISTRY.register("ericspawn_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.ERICSPAWN, -15007489, -1, new Item.Properties()));
		MAGGOTLORD_SPAWN_EGG = REGISTRY.register("maggotlord_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.MAGGOTLORD, -6684928, -10066432, new Item.Properties()));
		TZAANGORHALBERD_SPAWN_EGG = REGISTRY.register("tzaangorhalberd_spawn_egg", () -> new DeferredSpawnEggItem(HammercraftfantasyModEntities.TZAANGORHALBERD, -16763956, -1, new Item.Properties()));
		KEYOFTHRONE = REGISTRY.register("keyofthrone", KeyofthroneItem::new);
		KEYOFLIBRARY = REGISTRY.register("keyoflibrary", KeyoflibraryItem::new);
		KEYOFPALACE = REGISTRY.register("keyofpalace", KeyofpalaceItem::new);
		DEMONSTEELSWORD = REGISTRY.register("demonsteelsword", DemonsteelswordItem::new);
		DEMONSTEELAXE = REGISTRY.register("demonsteelaxe", DemonsteelaxeItem::new);
		DEMONSTEELPICKAXE = REGISTRY.register("demonsteelpickaxe", DemonsteelpickaxeItem::new);
		DEMONSTEELSHOVEL = REGISTRY.register("demonsteelshovel", DemonsteelshovelItem::new);
		DEMONSTEELHOE = REGISTRY.register("demonsteelhoe", DemonsteelhoeItem::new);
		DEMONSTEELARMOR_HELMET = REGISTRY.register("demonsteelarmor_helmet", DemonsteelarmorItem.Helmet::new);
		DEMONSTEELARMOR_CHESTPLATE = REGISTRY.register("demonsteelarmor_chestplate", DemonsteelarmorItem.Chestplate::new);
		DEMONSTEELARMOR_LEGGINGS = REGISTRY.register("demonsteelarmor_leggings", DemonsteelarmorItem.Leggings::new);
		DEMONSTEELARMOR_BOOTS = REGISTRY.register("demonsteelarmor_boots", DemonsteelarmorItem.Boots::new);
		CHANGINGGLASS = block(HammercraftfantasyModBlocks.CHANGINGGLASS);
		MAZECRYSTAL = block(HammercraftfantasyModBlocks.MAZECRYSTAL);
		RITUALDAGGER = REGISTRY.register("ritualdagger", RitualdaggerItem::new);
		FLAMERSHEAD = REGISTRY.register("flamershead", FlamersheadItem::new);
		TRICKYSTONEBRICK = block(HammercraftfantasyModBlocks.TRICKYSTONEBRICK);
		KCHAMP_HELMET = REGISTRY.register("kchamp_helmet", KchampItem.Helmet::new);
		KCHAMP_CHESTPLATE = REGISTRY.register("kchamp_chestplate", KchampItem.Chestplate::new);
		KCHAMP_LEGGINGS = REGISTRY.register("kchamp_leggings", KchampItem.Leggings::new);
		KCHAMP_BOOTS = REGISTRY.register("kchamp_boots", KchampItem.Boots::new);
		NCHAMP_HELMET = REGISTRY.register("nchamp_helmet", NchampItem.Helmet::new);
		NCHAMP_CHESTPLATE = REGISTRY.register("nchamp_chestplate", NchampItem.Chestplate::new);
		NCHAMP_LEGGINGS = REGISTRY.register("nchamp_leggings", NchampItem.Leggings::new);
		NCHAMP_BOOTS = REGISTRY.register("nchamp_boots", NchampItem.Boots::new);
		TCHAMP_HELMET = REGISTRY.register("tchamp_helmet", TchampItem.Helmet::new);
		TCHAMP_CHESTPLATE = REGISTRY.register("tchamp_chestplate", TchampItem.Chestplate::new);
		TCHAMP_LEGGINGS = REGISTRY.register("tchamp_leggings", TchampItem.Leggings::new);
		TCHAMP_BOOTS = REGISTRY.register("tchamp_boots", TchampItem.Boots::new);
		SCHAMP_HELMET = REGISTRY.register("schamp_helmet", SchampItem.Helmet::new);
		SCHAMP_CHESTPLATE = REGISTRY.register("schamp_chestplate", SchampItem.Chestplate::new);
		SCHAMP_LEGGINGS = REGISTRY.register("schamp_leggings", SchampItem.Leggings::new);
		SCHAMP_BOOTS = REGISTRY.register("schamp_boots", SchampItem.Boots::new);
		ALTAROFSUFFERING = block(HammercraftfantasyModBlocks.ALTAROFSUFFERING);
		K_CHAMPION_SUMMON_ALTAR = block(HammercraftfantasyModBlocks.K_CHAMPION_SUMMON_ALTAR);
		N_CHAMPION_SUMMON_ALTAR = block(HammercraftfantasyModBlocks.N_CHAMPION_SUMMON_ALTAR);
		T_CHAMPION_SUMMON_ALTAR = block(HammercraftfantasyModBlocks.T_CHAMPION_SUMMON_ALTAR);
		S_CHAMPION_SUMMON_ALTAR = block(HammercraftfantasyModBlocks.S_CHAMPION_SUMMON_ALTAR);
		RINGOFLUST_HELMET = REGISTRY.register("ringoflust_helmet", RingoflustItem.Helmet::new);
		CRYSTALGRASS = block(HammercraftfantasyModBlocks.CRYSTALGRASS);
		DEMONSTEELORE = block(HammercraftfantasyModBlocks.DEMONSTEELORE);
		DEMONSTRUENAME = REGISTRY.register("demonstruename", DemonstruenameItem::new);
		SILVERSHARPSWORD = REGISTRY.register("silversharpsword", SilversharpswordItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}